# Generated by Django 5.2.6 on 2026-08-08 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace_perfiles_constructora", "0001_initial"),
        ("marketplace_publicaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score_match",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("automatico", "Automático — sistema"),
                            ("constructora_interesada", "Interés directo constructora"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("sugerido", "Sugerido por el sistema"),
                            ("notificado", "Constructora notificada"),
                            ("interesada", "Constructora interesada"),
                            ("rechazado_const", "Rechazado por constructora"),
                            ("rechazado_hab", "Rechazado por HAB"),
                            ("en_negociacion", "En negociación formal"),
                        ],
                        db_index=True,
                        default="sugerido",
                        max_length=30,
                    ),
                ),
                ("motivo_rechazo", models.TextField(blank=True)),
                ("nota_constructora", models.TextField(blank=True)),
                ("nota_interna", models.TextField(blank=True)),
                ("notificado_en", models.DateTimeField(blank=True, null=True)),
                ("respondido_en", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "constructora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="marketplace_perfiles_constructora.perfilconstructoramp",
                    ),
                ),
                (
                    "publicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="marketplace_publicaciones.publicacioninmueble",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "ordering": ["-score_match", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["estado", "publicacion"],
                        name="marketplace_estado_d41952_idx",
                    ),
                    models.Index(
                        fields=["constructora", "estado"],
                        name="marketplace_constru_11b8ff_idx",
                    ),
                ],
                "unique_together": {("publicacion", "constructora")},
            },
        ),
    ]
