# Generated by Django 5.0.6 on 2026-05-24 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_estructuracion', models.CharField(default='gpt-4o', max_length=100)),
                ('modelo_bot_whatsapp', models.CharField(default='gpt-4o', max_length=100)),
                ('modelo_scoring', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('temperatura_bot', models.DecimalField(decimal_places=2, default=0.7, max_digits=3)),
                ('temperatura_estructuracion', models.DecimalField(decimal_places=2, default=0.3, max_digits=3)),
                ('max_tokens_respuesta_bot', models.IntegerField(default=500)),
                ('max_tokens_estructuracion', models.IntegerField(default=4000)),
                ('ia_bot_activa_global', models.BooleanField(default=True)),
                ('escalar_tras_n_mensajes', models.IntegerField(default=15)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración IA',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionScraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrios_objetivo', models.JSONField(default=list)),
                ('localidades', models.JSONField(default=list)),
                ('tipos_predio', models.JSONField(default=list)),
                ('estrato_min', models.IntegerField(default=3)),
                ('estrato_max', models.IntegerField(default=6)),
                ('precio_min', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('precio_max', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('area_lote_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frecuencia_cron', models.CharField(default='0 6 * * *', max_length=50)),
                ('max_paginas', models.IntegerField(default=20)),
                ('delay_entre_paginas', models.IntegerField(default=3)),
                ('umbral_score_auto_viable', models.IntegerField(default=65)),
                ('umbral_score_auto_noviable', models.IntegerField(default=30)),
                ('fuente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_avanzada', to='scraping.fuentescraping')),
            ],
            options={
                'verbose_name': 'Configuración de scraping',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.JSONField()),
                ('tipo', models.CharField(choices=[('string', 'Texto'), ('integer', 'Entero'), ('boolean', 'Booleano'), ('json', 'JSON'), ('secret', 'Secreto')], default='string', max_length=20)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('scraping', 'Scraping'), ('ia', 'IA'), ('whatsapp', 'WhatsApp'), ('notificaciones', 'Notificaciones'), ('general', 'General')], default='general', max_length=20)),
                ('editable_frontend', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuraciones del sistema',
                'ordering': ['categoria', 'clave'],
            },
        ),
    ]
