# Generated by Django 5.2.6 on 2026-08-08 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_user_role_permisomodulo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudCertificacionConstructora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_empresa", models.CharField(max_length=200)),
                ("nit", models.CharField(max_length=20)),
                ("contacto_nombre", models.CharField(max_length=200)),
                ("contacto_email", models.EmailField(max_length=254)),
                ("contacto_cargo", models.CharField(max_length=100)),
                ("contacto_telefono", models.CharField(max_length=20)),
                ("descripcion_empresa", models.TextField()),
                ("anios_experiencia", models.IntegerField()),
                ("proyectos_ejecutados", models.IntegerField()),
                ("zonas_interes", models.JSONField(blank=True, default=list)),
                ("tipos_proyecto", models.JSONField(blank=True, default=list)),
                (
                    "inversion_disponible",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=25, null=True
                    ),
                ),
                ("documentos", models.JSONField(blank=True, default=list)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("recibida", "Solicitud recibida"),
                            ("en_revision", "En revisión"),
                            ("docs_faltantes", "Documentos faltantes"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="recibida",
                        max_length=20,
                    ),
                ),
                ("notas_revision", models.TextField(blank=True)),
                ("documentos_faltantes", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "revisada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_certificacion_revisadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de certificación",
                "verbose_name_plural": "Solicitudes de certificación",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerfilConstructoraMP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_comercial", models.CharField(max_length=200)),
                ("nit", models.CharField(max_length=20, unique=True)),
                ("logo_url", models.URLField(blank=True)),
                ("descripcion", models.TextField()),
                ("anio_fundacion", models.IntegerField(blank=True, null=True)),
                ("sitio_web", models.URLField(blank=True)),
                (
                    "estado_certificacion",
                    models.CharField(
                        choices=[
                            ("pendiente", "Solicitud pendiente"),
                            ("en_revision", "En revisión por HAB"),
                            ("certificada", "Certificada por HAB"),
                            ("suspendida", "Suspendida"),
                            ("rechazada", "Rechazada"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "nivel_certificacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("basico", "Básico"),
                            ("verificado", "Verificado"),
                            ("premium", "Premium"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("certificada_en", models.DateTimeField(blank=True, null=True)),
                ("vence_certificacion", models.DateField(blank=True, null=True)),
                ("notas_certificacion", models.TextField(blank=True)),
                ("zonas_interes", models.JSONField(blank=True, default=list)),
                ("tipos_proyecto", models.JSONField(blank=True, default=list)),
                (
                    "inversion_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=25, null=True
                    ),
                ),
                (
                    "inversion_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=25, null=True
                    ),
                ),
                ("unidades_min", models.IntegerField(blank=True, null=True)),
                ("unidades_max", models.IntegerField(blank=True, null=True)),
                ("proyectos_ejecutados", models.IntegerField(default=0)),
                (
                    "m2_construidos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("referencias", models.JSONField(blank=True, default=list)),
                (
                    "documentos_certificacion",
                    models.JSONField(blank=True, default=list),
                ),
                ("total_intereses_expresados", models.IntegerField(default=0)),
                ("total_negociaciones", models.IntegerField(default=0)),
                ("total_cierres", models.IntegerField(default=0)),
                (
                    "tasa_cierre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certificada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="constructoras_certificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "constructora",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_marketplace",
                        to="accounts.constructora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil constructora marketplace",
                "verbose_name_plural": "Perfiles constructoras marketplace",
                "indexes": [
                    models.Index(
                        fields=["estado_certificacion"],
                        name="marketplace_estado__cf3ebd_idx",
                    ),
                    models.Index(
                        fields=["vence_certificacion"],
                        name="marketplace_vence_c_52fb28_idx",
                    ),
                ],
            },
        ),
    ]
