# Generated by Django 5.0.6 on 2026-05-24 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('interna', 'Interna'), ('decision', 'Decisión'), ('alerta', 'Alerta'), ('seguimiento', 'Seguimiento')], default='interna', max_length=20)),
                ('es_fijada', models.BooleanField(default=False)),
                ('adjuntos', models.JSONField(default=list)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-es_fijada', '-creada_en'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='shared_nota_content_26764f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PipelinePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('orden', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Posición en pipeline',
                'ordering': ['orden'],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
