# Generated by Django 5.0.6 on 2026-05-24 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('leads', '0001_initial'),
        ('scraping', '0001_initial'),
        ('viabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fase', models.CharField(choices=[('estructuracion', 'Estructuración'), ('presentado', 'Presentado'), ('en_negociacion', 'En negociación'), ('promesa', 'Promesa'), ('en_obra', 'En obra'), ('entregado', 'Entregado'), ('descartado', 'Descartado')], db_index=True, default='estructuracion', max_length=20)),
                ('fee_estructuracion', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pct_gerencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pct_ventas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_total_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('ingresos_estructuracion_real', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ingresos_gerencia_real', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ingresos_ventas_real', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('estructuracion_generada_en', models.DateTimeField(blank=True, null=True)),
                ('presentacion_url', models.URLField(blank=True)),
                ('doc_estructuracion_url', models.URLField(blank=True)),
                ('fecha_estructuracion', models.DateField(blank=True, null=True)),
                ('fecha_presentacion', models.DateField(blank=True, null=True)),
                ('fecha_inicio_obra', models.DateField(blank=True, null=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='viabilidad.analisisviabilidad')),
                ('constructoras', models.ManyToManyField(blank=True, to='accounts.constructora')),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_gestionados', to=settings.AUTH_USER_MODEL)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='scraping.predio')),
                ('predios_consolidados', models.ManyToManyField(blank=True, related_name='proyectos_consolidados', to='scraping.predio')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HitoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_planeada', models.DateField()),
                ('fecha_real', models.DateField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('evidencia_url', models.URLField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Hito del proyecto',
                'ordering': ['fecha_planeada'],
            },
        ),
        migrations.CreateModel(
            name='EstructuracionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('es_vigente', models.BooleanField(default=True)),
                ('generada_por_ia', models.BooleanField(default=False)),
                ('area_lote', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('area_construida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('area_vendible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidades_totales', models.IntegerField(default=0)),
                ('unidades_vis', models.IntegerField(default=0)),
                ('unidades_no_vis', models.IntegerField(default=0)),
                ('pisos', models.IntegerField(default=0)),
                ('precio_m2_vis', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('precio_m2_no_vis', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('precio_m2_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ingresos_brutos', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('costo_terreno', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('costo_construccion', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('costo_urbanismo', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('costo_diseno', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('costo_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('costo_gerencia', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('costo_legales', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('costos_imprevistos', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('utilidad_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('margen_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('utilidad_neta', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('margen_neto', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tir_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('punto_equilibrio_uds', models.IntegerField(blank=True, null=True)),
                ('valor_max_predio', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('hab_fee_estructuracion', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('hab_fee_gerencia', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('hab_fee_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('hab_ingreso_total', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('flujo_caja_mensual', models.JSONField(default=list)),
                ('resumen_ejecutivo', models.TextField(blank=True)),
                ('fortalezas', models.JSONField(default=list)),
                ('riesgos', models.JSONField(default=list)),
                ('recomendaciones', models.JSONField(default=list)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('generada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estructuraciones', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Estructuración del proyecto',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_aporte', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('condicion_aporte', models.TextField(blank=True)),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.propietario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Propietario del proyecto',
                'unique_together': {('proyecto', 'propietario')},
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='propietarios',
            field=models.ManyToManyField(blank=True, related_name='proyectos', through='proyectos.ProyectoPropietario', to='leads.propietario'),
        ),
    ]
