# Generated by Django 5.0.6 on 2026-05-24 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConocimientoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('norma', 'Norma'), ('ejemplo_proyecto', 'Ejemplo de proyecto'), ('instruccion', 'Instrucción'), ('tabla_precios', 'Tabla de precios'), ('otro', 'Otro')], default='instruccion', max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('texto_plano', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='ia/knowledge/')),
                ('archivo_tipo', models.CharField(blank=True, max_length=20)),
                ('contenido_extraido', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('aplica_a', models.CharField(choices=[('estructuracion', 'Estructuración'), ('scoring', 'Scoring'), ('bot', 'Bot'), ('todos', 'Todos')], default='todos', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Base de conocimiento IA',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PromptIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('modulo', models.CharField(choices=[('estructuracion', 'Estructuración'), ('scoring', 'Scoring'), ('bot_inicio', 'Bot — inicio'), ('bot_presentacion', 'Bot — presentación'), ('bot_objeciones', 'Bot — objeciones'), ('bot_agendamiento', 'Bot — agendamiento'), ('prefactibilidad', 'Prefactibilidad')], max_length=30, unique=True)),
                ('prompt_sistema', models.TextField()),
                ('prompt_usuario', models.TextField()),
                ('variables_disponibles', models.JSONField(default=list)),
                ('activo', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt IA',
            },
        ),
    ]
