# Generated by Django 5.0.6 on 2026-05-25 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('modulo', models.CharField(choices=[('bot_whatsapp', 'Bot WhatsApp'), ('scoring', 'Scoring de predios'), ('estructuracion', 'Estructuración financiera'), ('prefactibilidad', 'Prefactibilidad')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('modelo_ia', models.CharField(default='gpt-4o', max_length=100)),
                ('temperatura', models.DecimalField(decimal_places=2, default=0.7, max_digits=3)),
                ('max_tokens', models.IntegerField(default=500)),
                ('activo', models.BooleanField(default=True)),
                ('es_principal', models.BooleanField(default=False, help_text='Solo un agente por módulo puede ser principal')),
                ('instrucciones_extra', models.TextField(blank=True, help_text='Instrucciones adicionales que se añaden al prompt base')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de agente',
                'ordering': ['modulo', 'nombre'],
            },
        ),
    ]
