# Generated by Django 5.0.6 on 2026-05-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_configuracionagente'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconocimientoia',
            name='embedding_cache',
            field=models.TextField(blank=True, default='', help_text='Cache JSON de embeddings RAG para búsqueda semántica'),
        ),
    ]
