# Generated by Django 5.0.6 on 2026-05-24 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('scraping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_phone_id', models.CharField(max_length=50)),
                ('wa_contact_phone', models.CharField(db_index=True, max_length=20)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada'), ('escalada', 'Escalada')], db_index=True, default='activa', max_length=20)),
                ('ia_activa', models.BooleanField(default=True)),
                ('ia_desactivada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_desactivacion', models.CharField(blank=True, max_length=200)),
                ('etapa_bot', models.CharField(choices=[('inicio', 'Inicio'), ('calificacion', 'Calificación'), ('presentacion', 'Presentación'), ('objeciones', 'Objeciones'), ('agendamiento', 'Agendamiento'), ('cerrada', 'Cerrada')], default='inicio', max_length=20)),
                ('contexto', models.JSONField(default=dict)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_mensaje', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('ia_desactivada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats_tomados', to=settings.AUTH_USER_MODEL)),
                ('predio_contexto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping.predio')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='leads.propietario')),
            ],
            options={
                'verbose_name': 'Conversación',
                'ordering': ['-ultimo_mensaje'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_message_id', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(choices=[('entrante', 'Entrante'), ('saliente', 'Saliente')], max_length=10)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('documento', 'Documento'), ('audio', 'Audio'), ('plantilla', 'Plantilla')], default='texto', max_length=20)),
                ('contenido', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('generado_por_ia', models.BooleanField(default=False)),
                ('enviado_en', models.DateTimeField()),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='bot.conversacion')),
            ],
            options={
                'ordering': ['enviado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['wa_contact_phone', 'estado'], name='bot_convers_wa_cont_d24b73_idx'),
        ),
    ]
