# Generated by Django 5.2.6 on 2026-08-08 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace_matching", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Negociacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fase",
                    models.CharField(
                        choices=[
                            ("inicio", "Inicio — presentación formal"),
                            ("due_diligence", "Due diligence"),
                            ("oferta_inicial", "Oferta inicial de constructora"),
                            ("contrapropuesta", "Contrapropuesta"),
                            ("acuerdo_verbal", "Acuerdo verbal"),
                            ("documentacion", "Preparación de documentos"),
                            ("firma", "Firma"),
                            ("cerrada_exitosa", "Cerrada — éxito"),
                            ("cerrada_sin_exito", "Cerrada — sin acuerdo"),
                        ],
                        default="inicio",
                        max_length=30,
                    ),
                ),
                (
                    "valor_oferta_constructora",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "tipo_compensacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dinero", "Dinero"),
                            ("unidades", "Unidades"),
                            ("mixto", "Mixto"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("unidades_ofrecidas", models.IntegerField(blank=True, null=True)),
                (
                    "valor_dinero_adicional",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("condiciones_especiales", models.TextField(blank=True)),
                (
                    "fee_estructuracion_hab",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "fee_gerencia_hab",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "fee_ventas_hab",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("tipo_garantia", models.CharField(blank=True, max_length=30)),
                ("descripcion_garantia", models.TextField(blank=True)),
                ("fiduciaria", models.CharField(blank=True, max_length=200)),
                ("documentos", models.JSONField(blank=True, default=list)),
                ("fecha_cierre_meta", models.DateField(blank=True, null=True)),
                ("cerrada_en", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asesor_hab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="negociaciones_marketplace",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="negociacion",
                        to="marketplace_matching.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Negociación",
                "verbose_name_plural": "Negociaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventoNegociacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        choices=[
                            ("hab", "HAB"),
                            ("constructora", "Constructora"),
                            ("propietario", "Propietario"),
                            ("sistema", "Sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("datos", models.JSONField(blank=True, default=dict)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_negociacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "negociacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="marketplace_negociaciones.negociacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de negociación",
                "verbose_name_plural": "Eventos de negociación",
                "ordering": ["-creado_en"],
            },
        ),
    ]
