# Generated by Django 5.0.6 on 2026-05-24 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisViabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_pot', models.CharField(blank=True, max_length=100)),
                ('indice_construccion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('indice_ocupacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura_max_pisos', models.IntegerField(blank=True, null=True)),
                ('uso_suelo', models.CharField(blank=True, max_length=200)),
                ('densidad_max_uds', models.IntegerField(blank=True, null=True)),
                ('area_edificable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidades_proyectadas', models.IntegerField(blank=True, null=True)),
                ('precio_m2_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_bruto_proyecto', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('costo_construccion', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('valor_max_predio', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('utilidad_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('margen_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('es_viable', models.BooleanField(null=True)),
                ('razon_no_viabilidad', models.TextField(blank=True)),
                ('score_viabilidad', models.IntegerField(blank=True, null=True)),
                ('justificacion_ia', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('solicitado_en', models.DateTimeField(auto_now_add=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('predio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='scraping.predio')),
            ],
            options={
                'verbose_name': 'Análisis de viabilidad',
                'ordering': ['-solicitado_en'],
            },
        ),
    ]
