# Generated by Django 5.0.6 on 2026-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('administrativo', 'Administrativo'), ('finanzas', 'Finanzas'), ('estructuracion', 'Estructuración'), ('comercial', 'Comercial'), ('analista', 'Analista'), ('asesor', 'Asesor'), ('gerente', 'Gerente'), ('constructora', 'Constructora')], default='asesor', max_length=20),
        ),
        migrations.CreateModel(
            name='PermisoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('administrativo', 'Administrativo'), ('finanzas', 'Finanzas'), ('estructuracion', 'Estructuración'), ('comercial', 'Comercial'), ('analista', 'Analista'), ('asesor', 'Asesor'), ('gerente', 'Gerente'), ('constructora', 'Constructora')], max_length=30)),
                ('modulo', models.CharField(choices=[('dashboard', 'Dashboard general'), ('financiero', 'Dashboard financiero'), ('predios', 'Predios / Scraping'), ('viabilidad', 'Análisis de viabilidad'), ('propietarios', 'Propietarios CRM'), ('leads', 'Leads CRM'), ('calendario', 'Calendario de citas'), ('bot', 'WhatsApp Bot'), ('proyectos', 'Proyectos'), ('estructuracion', 'Estructuración financiera'), ('ia', 'Inteligencia Artificial'), ('configuracion', 'Configuración'), ('usuarios', 'Gestión de usuarios')], max_length=30)),
                ('puede_ver', models.BooleanField(default=False)),
                ('puede_editar', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permiso de módulo',
                'ordering': ['role', 'modulo'],
                'unique_together': {('role', 'modulo')},
            },
        ),
    ]
