# Generated by Django 5.2.6 on 2026-08-08 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace_negociaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Garantia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(blank=True, max_length=50)),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "negociacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garantias",
                        to="marketplace_negociaciones.negociacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Garantía",
                "verbose_name_plural": "Garantías",
            },
        ),
    ]
