# Generated by Django 5.2.6 on 2026-08-08 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_user_role_permisomodulo"),
        ("marketplace_perfiles_constructora", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructoraPortalUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefono", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("password_hash", models.CharField(max_length=128)),
                ("otp_code", models.CharField(blank=True, max_length=6)),
                ("otp_expires_at", models.DateTimeField(blank=True, null=True)),
                ("otp_intentos", models.IntegerField(default=0)),
                ("telefono_verificado", models.BooleanField(default=False)),
                ("email_verificado", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("bloqueado_hasta", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ultimo_login", models.DateTimeField(blank=True, null=True)),
                (
                    "constructora",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_user",
                        to="accounts.constructora",
                    ),
                ),
                (
                    "perfil_marketplace",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_user",
                        to="marketplace_perfiles_constructora.perfilconstructoramp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal User — Constructora",
                "verbose_name_plural": "Portal Users — Constructoras",
                "indexes": [
                    models.Index(
                        fields=["telefono"], name="auth_constr_telefon_fa6ea5_idx"
                    ),
                    models.Index(fields=["email"], name="auth_constr_email_2c5475_idx"),
                ],
            },
        ),
    ]
