# Generated by Django 5.2.6 on 2026-08-08 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropietarioPortalUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefono", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("password_hash", models.CharField(max_length=128)),
                ("otp_code", models.CharField(blank=True, max_length=6)),
                ("otp_expires_at", models.DateTimeField(blank=True, null=True)),
                ("otp_intentos", models.IntegerField(default=0)),
                ("telefono_verificado", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("bloqueado_hasta", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ultimo_login", models.DateTimeField(blank=True, null=True)),
                (
                    "propietario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_user",
                        to="leads.propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal User — Propietario",
                "verbose_name_plural": "Portal Users — Propietarios",
                "indexes": [
                    models.Index(
                        fields=["telefono"], name="auth_propie_telefon_2a907c_idx"
                    )
                ],
            },
        ),
    ]
