# Generated by Django 5.0.6 on 2026-05-24 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cedula', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('interesado', 'Interesado'), ('calificado', 'Calificado'), ('cita_agendada', 'Cita agendada'), ('propuesta_enviada', 'Propuesta enviada'), ('en_negociacion', 'En negociación'), ('promesa_firmada', 'Promesa firmada'), ('descartado', 'Descartado')], db_index=True, default='nuevo', max_length=30)),
                ('temperatura', models.CharField(choices=[('frio', 'Frío'), ('tibio', 'Tibio'), ('caliente', 'Caliente')], default='frio', max_length=10)),
                ('fuente_origen', models.CharField(blank=True, max_length=100)),
                ('primer_contacto', models.DateTimeField(blank=True, null=True)),
                ('ultimo_contacto', models.DateTimeField(blank=True, null=True)),
                ('proxima_accion', models.DateTimeField(blank=True, null=True)),
                ('nota_proxima_accion', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('etiquetas', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('predio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping.predio')),
            ],
            options={
                'verbose_name': 'Lead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteraccionLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('llamada', 'Llamada'), ('email', 'Email'), ('visita', 'Visita'), ('cita', 'Cita'), ('nota_interna', 'Nota interna')], max_length=20)),
                ('descripcion', models.TextField()),
                ('resultado', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='leads.lead')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('videollamada', 'Videollamada'), ('telefonica', 'Telefónica')], max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=300)),
                ('url_meet', models.URLField(blank=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('no_show', 'No show')], default='programada', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='leads.lead')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('persona_natural', 'Persona natural'), ('persona_juridica', 'Persona jurídica')], default='persona_natural', max_length=20)),
                ('cedula_nit', models.CharField(blank=True, max_length=20)),
                ('telefono_principal', models.CharField(max_length=20)),
                ('telefono_secundario', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('direccion_residencia', models.CharField(blank=True, max_length=300)),
                ('estado_contacto', models.CharField(choices=[('sin_contactar', 'Sin contactar'), ('contactado', 'Contactado'), ('interesado', 'Interesado'), ('calificado', 'Calificado'), ('en_negociacion', 'En negociación'), ('firmado', 'Firmado'), ('descartado', 'Descartado')], db_index=True, default='sin_contactar', max_length=20)),
                ('temperatura', models.CharField(choices=[('frio', 'Frío'), ('tibio', 'Tibio'), ('caliente', 'Caliente')], default='frio', max_length=10)),
                ('fuente_origen', models.CharField(blank=True, max_length=100)),
                ('etiquetas', models.JSONField(default=list)),
                ('primer_contacto', models.DateTimeField(blank=True, null=True)),
                ('ultimo_contacto', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asesor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propietarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.propietario'),
        ),
        migrations.CreateModel(
            name='PropietarioPredio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_propiedad', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('rol', models.CharField(choices=[('propietario', 'Propietario'), ('heredero', 'Heredero'), ('apoderado', 'Apoderado'), ('arrendatario', 'Arrendatario')], default='propietario', max_length=20)),
                ('es_contacto_principal', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.predio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.propietario')),
            ],
            options={
                'verbose_name': 'Propietario-Predio',
                'unique_together': {('propietario', 'predio', 'rol')},
            },
        ),
        migrations.AddField(
            model_name='propietario',
            name='predios',
            field=models.ManyToManyField(blank=True, related_name='propietarios', through='leads.PropietarioPredio', to='scraping.predio'),
        ),
    ]
