# Generated by Django 5.2.6 on 2026-08-08 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0001_initial"),
        ("proyectos", "0001_initial"),
        ("scraping", "0002_predio_pipeline_operativo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicacionInmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("casa", "Casa unifamiliar"),
                            ("lote", "Lote sin construir"),
                            ("apartamento", "Apartamento"),
                            ("local", "Local comercial"),
                            ("bodega", "Bodega"),
                        ],
                        max_length=20,
                    ),
                ),
                ("direccion", models.CharField(max_length=300)),
                ("barrio", models.CharField(max_length=200)),
                ("localidad", models.CharField(max_length=200)),
                ("ciudad", models.CharField(default="Bogotá", max_length=100)),
                (
                    "latitud",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("area_lote", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "area_construida",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("pisos", models.IntegerField(blank=True, null=True)),
                ("habitaciones", models.IntegerField(blank=True, null=True)),
                ("banos", models.IntegerField(blank=True, null=True)),
                ("estrato", models.IntegerField()),
                ("anio_construccion", models.IntegerField(blank=True, null=True)),
                (
                    "estado_inmueble",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("muy_bueno", "Muy bueno — listo para habitar"),
                            ("bueno", "Bueno — mantenimiento menor"),
                            ("regular", "Regular — requiere remodelación"),
                            ("demolicion", "Para demolición"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "precio_esperado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("acepta_aporte", models.BooleanField(default=True)),
                ("fotos", models.JSONField(blank=True, default=list)),
                ("documentos", models.JSONField(blank=True, default=list)),
                ("identidad_verificada", models.BooleanField(default=False)),
                ("propiedad_verificada", models.BooleanField(default=False)),
                ("verificado_en", models.DateTimeField(blank=True, null=True)),
                ("notas_verificacion", models.TextField(blank=True)),
                (
                    "score_prefactibilidad",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("tags_prefact", models.JSONField(blank=True, default=list)),
                ("metricas_prefact", models.JSONField(blank=True, default=dict)),
                ("prefact_calculada_en", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("en_revision", "En revisión por HAB"),
                            ("activa", "Activa — visible"),
                            ("en_negociacion", "En negociación"),
                            ("cerrada_exitosa", "Cerrada — acuerdo logrado"),
                            ("cerrada_sin_exito", "Cerrada — sin acuerdo"),
                            ("rechazada", "Rechazada"),
                        ],
                        db_index=True,
                        default="borrador",
                        max_length=30,
                    ),
                ),
                ("motivo_rechazo", models.TextField(blank=True)),
                ("visible_constructoras", models.BooleanField(default=False)),
                ("datos_anonimizados", models.BooleanField(default=True)),
                ("publicado_en", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "predio_vinculado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publicacion_marketplace",
                        to="scraping.predio",
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publicaciones",
                        to="leads.propietario",
                    ),
                ),
                (
                    "proyecto_generado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publicacion_origen",
                        to="proyectos.proyecto",
                    ),
                ),
                (
                    "verificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publicaciones_verificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Publicación de inmueble",
                "verbose_name_plural": "Publicaciones de inmuebles",
                "ordering": ["-score_prefactibilidad", "-publicado_en"],
            },
        ),
        migrations.CreateModel(
            name="EstructuracionExpress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unidades_proyectadas", models.IntegerField(blank=True, null=True)),
                (
                    "area_vendible_est",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "ingresos_brutos_est",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "costo_total_est",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "margen_bruto_est",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "roi_est",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "valor_max_predio_est",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("resumen", models.TextField(blank=True)),
                ("datos_completos", models.JSONField(blank=True, default=dict)),
                ("modelo_ia", models.CharField(blank=True, max_length=100)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "publicacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estructuracion_express",
                        to="marketplace_publicaciones.publicacioninmueble",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estructuración express",
                "verbose_name_plural": "Estructuraciones express",
            },
        ),
        migrations.AddIndex(
            model_name="publicacioninmueble",
            index=models.Index(
                fields=["estado", "visible_constructoras"],
                name="marketplace_estado_297d07_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publicacioninmueble",
            index=models.Index(
                fields=["barrio", "localidad", "estado"],
                name="marketplace_barrio_a56113_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publicacioninmueble",
            index=models.Index(
                fields=["score_prefactibilidad", "estado"],
                name="marketplace_score_p_490d34_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publicacioninmueble",
            index=models.Index(
                fields=["propietario", "estado"], name="marketplace_propiet_a3acc4_idx"
            ),
        ),
    ]
