# Generated by Django 5.0.6 on 2026-05-24 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteScraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url_base', models.URLField()),
                ('activo', models.BooleanField(default=True)),
                ('configuracion', models.JSONField(default=dict)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fuente de scraping',
            },
        ),
        migrations.CreateModel(
            name='ZonaPOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=200)),
                ('barrio', models.CharField(blank=True, db_index=True, max_length=200)),
                ('localidad', models.CharField(max_length=100)),
                ('uso_suelo_principal', models.CharField(max_length=100)),
                ('indice_construccion', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('indice_ocupacion', models.DecimalField(decimal_places=2, default=0.6, max_digits=4)),
                ('altura_max_pisos', models.IntegerField(default=6)),
                ('densidad_max_viv', models.IntegerField(blank=True, null=True)),
                ('es_zona_densificacion', models.BooleanField(default=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zona POT',
                'verbose_name_plural': 'Zonas POT',
            },
        ),
        migrations.CreateModel(
            name='EjecucionScraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('predios_encontrados', models.IntegerField(default=0)),
                ('predios_nuevos', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('corriendo', 'Corriendo'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='scraping.fuentescraping')),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_origen', models.URLField(unique=True)),
                ('codigo_externo', models.CharField(blank=True, max_length=100)),
                ('barrio', models.CharField(db_index=True, max_length=200)),
                ('localidad', models.CharField(max_length=200)),
                ('ciudad', models.CharField(default='Bogotá', max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('lote', 'Lote'), ('apartamento', 'Apartamento'), ('local', 'Local')], max_length=20)),
                ('area_lote', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_construida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estrato', models.IntegerField(blank=True, db_index=True, null=True)),
                ('pisos', models.IntegerField(blank=True, null=True)),
                ('anio_construccion', models.IntegerField(blank=True, null=True)),
                ('precio_publicado', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('precio_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_analisis', 'En análisis'), ('viable', 'Viable'), ('no_viable', 'No viable'), ('contactado', 'Contactado'), ('descartado', 'Descartado')], db_index=True, default='nuevo', max_length=20)),
                ('imagenes', models.JSONField(default=list)),
                ('descripcion_raw', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('score_prefactibilidad', models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=5, null=True)),
                ('tags', models.JSONField(default=list)),
                ('tags_manuales', models.JSONField(default=list)),
                ('metricas_prefact', models.JSONField(default=dict)),
                ('detalle_scores', models.JSONField(default=dict)),
                ('prefact_calculada_en', models.DateTimeField(blank=True, null=True)),
                ('precio_m2_referencia_barrio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('primera_deteccion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predios', to='scraping.fuentescraping')),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
                'ordering': ['-primera_deteccion'],
                'indexes': [models.Index(fields=['estado', 'score_prefactibilidad'], name='scraping_pr_estado_e6e4d0_idx'), models.Index(fields=['barrio', 'estrato'], name='scraping_pr_barrio_da2699_idx')],
            },
        ),
    ]
